cxx         := "zig c++"
# cxx-args    := "-Wall -Wextra -Werror -pedantic" # -O2
cxx-args    := "" 

alias default := main

setup:
    mkdir -p build
    mkdir -p build/cache

# Builds the main
main: setup
    just build "./src/social_network.cpp ./src/user.cpp ./src/network.cpp" main
    ./build/main

clean:
    rm -r build

tests: setup
    just build "./src/tests/test_user_1.cpp ./src/user.cpp" "test-user-1"
    just build "./src/tests/test_user_2.cpp ./src/user.cpp" "test-user-2"
    just build "./src/tests/test_user_3.cpp ./src/user.cpp" "test-user-3"
    just build "./src/tests/test_user_4.cpp ./src/user.cpp" "test-user-4"

    just build "./src/tests/test_user_add_duplicate_friend.cpp ./src/user.cpp" "test-user-adddup"
    just build "./src/tests/test_user_add_friend.cpp ./src/user.cpp" "test-user-add"
    just build "./src/tests/test_user_delete_friend.cpp ./src/user.cpp" "test-user-delete"
    just build "./src/tests/test_user_get_friend_reference.cpp ./src/user.cpp" "test-user-get"

    just build "./src/tests/test_network_.cpp ./src/user.cpp ./src/network.cpp" "test-network"

    just build "./src/tests/test_network_add_connection.cpp ./src/user.cpp ./src/network.cpp" "test-network-add"
    just build "./src/tests/test_network_add_duplicate_connection.cpp ./src/user.cpp ./src/network.cpp" "test-network-adddup"
    just build "./src/tests/test_network_add_invalid_connection.cpp ./src/user.cpp ./src/network.cpp" "test-network-addbad"
    just build "./src/tests/test_network_add_user.cpp ./src/user.cpp ./src/network.cpp" "test-network-add-user"
    just build "./src/tests/test_network_delete_connection.cpp ./src/user.cpp ./src/network.cpp" "test-network-del-con"
    just build "./src/tests/test_network_delete_invalid_connection.cpp ./src/user.cpp ./src/network.cpp" "test-network-del-badcon"
    just build "./src/tests/test_network_delete_invalid_connection.cpp ./src/user.cpp ./src/network.cpp" "test-network-del-badcon"

    just build "./src/tests/test_network_get_id.cpp ./src/user.cpp ./src/network.cpp" "test-network-del-badcon"
    just build "./src/tests/test_network_get_user.cpp ./src/user.cpp ./src/network.cpp" "test-network-del-badcon"
    just build "./src/tests/test_network_get_user_nullptr.cpp ./src/user.cpp ./src/network.cpp" "test-network-del-badcon"
    just build "./src/tests/test_network_read_user.cpp ./src/user.cpp ./src/network.cpp" "test-network-read-user1"
    just build "./src/tests/test_network_read_user2.cpp ./src/user.cpp ./src/network.cpp" "test-network-read-user2"

test:
    just tests # 2>./build/log
    for f in build/test-*; do ./$f || exit; done

build files name:
    #!/bin/sh
    # set -euxo pipefail
    # name=$(echo {{files}} | cut -d. -f1 | sed -e 's@src/@@' |tr '/' '-')
    cache="build/cache/{{name}}"
    checksum="$(cat {{files}} | sha256sum)"
    if [ "$(echo $checksum)" != "$(cat $cache 2>/dev/null)" ]; then
        {{cxx}} {{cxx-args}} {{files}} -o "build/{{name}}" || exit
        echo $checksum > "$cache"
    fi

